# Overrides for preprod environment.
# Usage: docker compose -f docker-compose.yml -f docker-compose.preprod.yml --profile preprod up -d

services:
  app:
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SIDDHARTH_SECRET_KEY_PREPROD}
    networks:
      web:
        aliases:
          - app-preprod

  streamlit:
    networks:
      web:
        aliases:
          - streamlit-preprod
