# Overrides for preprod environment.
# Usage: docker compose -f docker-compose.yml -f docker-compose.preprod.yml --profile preprod up -d

services:
  app:
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SIDDHARTH_SECRET_KEY_PREPROD}
    ports:
      - "8001:8000"
    networks:
      web:
        aliases:
          - app-preprod

  streamlit:
    ports:
      - "127.0.0.1:8502:8501"
    networks:
      web:
        aliases:
          - streamlit-preprod
